# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test .NET projects

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Set user secrets
      run: cat ./BoardGameCommerceAPI/secrets_input.json | dotnet user-secrets set --project ./BoardGameCommerceAPI/BoardGameCommerceAPI.csproj
    - name: Restore dependencies API
      run: dotnet restore ./BoardGameCommerceAPI/BoardGameCommerceAPI.csproj 
    - name: Build API
      run: dotnet build ./BoardGameCommerceAPI/BoardGameCommerceAPI.csproj --no-restore
    - name: Restore dependencies WebApp
      run: dotnet restore ./BoardGameCommerceWebApp/BoardGameCommerce.csproj 
    - name: Build WepApp
      run: dotnet build ./BoardGameCommerceWebApp/BoardGameCommerce.csproj --no-restore
    - name: Restore dependencies Test API
      run: dotnet restore BoardGameCommerceAPI.IntegrationTests 
    - name: Build Test API
      run: dotnet build BoardGameCommerceAPI.IntegrationTests --no-restore
    - name: Test API
      run: dotnet test BoardGameCommerceAPI.IntegrationTests --verbosity normal --no-build
